### ISSUE TITLE
AI steals mouse focus

### ISSUE THREAD

**Issue by joshmiller17** [joshmiller17/spirecomm#12]
At certain delay rates (?) AI takes mouse focus and makes it difficult to do other things. Determine repro steps and debug workarounds.

**Comment by mutherr** [comment]
What delay rates have you experienced the bug at?

**Comment by joshmiller17** [comment]
Try 0.5

**Comment by joshmiller17** [comment]
It may not be related to delay rate, but to whether the StS window has focus.

**Comment by joshmiller17** [comment]
I think if you are encountering this bug, just give the StS window focus as it's starting up - it steals the mouse if the window never had focus.
