### ISSUE TITLE
MCTS

### ISSUE THREAD

**Issue by joshmiller17** [joshmiller17/spirecomm#18]
A function which takes as input:
- starting state
- MCTS parameters (e.g. iterations or timeout)

Each state will have:
1. A `getPossibleActions()` function
2. A `takeAction()` function which returns a new state
3. An `isTerminal()` function
4. A `getReward()` function (only valid if terminal)

MCTS will output the chosen action which leads to the best rewards

**Comment by joshmiller17** [comment]
Update: we can just use regular ol' MCTS. Maybe this one: https://pypi.org/project/mcts/

**Comment by mutherr** [comment]
It sounds like this is a nonissue, then. Having looked into the mcts package a bit, it looks pretty straightforward.
