### ISSUE TITLE
State diff / game state bugs

### ISSUE THREAD

**Issue by joshmiller17** [joshmiller17/spirecomm#30]
- [x] drawn cards are treated as discovered
- [x] When multiple enemies, dead enemies are still tracked even though they shouldn't be considered an available monster
- [x] `simulation_sanity_check` fails even for defends/strikes which it should be able to handle -- something weird is going on with which state it thinks it's computing
- [x] `simulation_sanity_check` fails for drawing a new hand of cards

**Comment by mutherr** [comment]
Why does "now" exist?

Also, what does the "discovered" state mean? Like, if drawn cards shouldn't be treated as discovered, what should be?

**Comment by joshmiller17** [comment]
Now is a label that helps me prioritize what I'm actively working on, or what I think is the next step, since some issues depend on others being completed first. "Discovered" should be if we gained a card from an attack/skill/power potion.

**Comment by mutherr** [comment]
Ahhh ok. Thanks!
